package com.ioevent.ioeventhumantaskhandlerstarter.domain;

public enum IOEventHeaders {
    CORRELATION_ID,STEP_NAME,INPUT,EVENT_TYPE,OUTPUT_EVENT,START_TIME,API_KEY,PROCESS_NAME,START_INSTANCE_TIME,IMPLICIT_START,IMPLICIT_END,
    ERROR_TYPE,ERROR_MESSAGE,ERROR_TRACE,RESUME,MESSAGE_KEY
}
