spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: '*'
  application:
    name: testHumanTask
servers:
  elasticsearch:
    url: http://localhost:9200
ioevent:
  application_name: Exemple1